apps/product/urls.py
from apps.product.views import *
from django.urls import path

from apps.shopping.views import BuyProductView

urlpatterns = [
	path('product-details/<int:pk>', ProductDetailView.as_view(), name='product-details'),
	path('product-details/<int:pk>', ProductDetailView.as_view(), name='product-details'),
	path('create-product', ProductCreateView.as_view(), name='create-product'),
	path('comparison/<int:pk1>,<int:pk2>', ProductCompareView.as_view(), name='comparison'),
	path('helpers/son_categories/<int:category_id>', get_category_childs_one_level,
		 name='get_category_childs_one_level')
]

backend_settings/urls.py
from django.conf import settings
from django.conf.urls.static import static

"""asd URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
import django.views.static

admin.site.site_header = "سخوف"
urlpatterns = [

	url(r'^media/(?P<path>.*)$', django.views.static.serve,
		{'document_root': settings.MEDIA_ROOT, 'show_indexes': settings.DEBUG}),
	path('admin/', admin.site.urls),
	path('', include(('apps.dashboard.urls', 'dashboard'), 'dashboard')),
	path('', include(('apps.product.urls', 'product'), 'product')),
	path('', include(('apps.landing.urls', 'landing'), 'landing')),
	path('', include(('apps.registeration.urls', 'registeration'), 'registeration')),
	path('', include(('apps.messaging.urls', 'messaging'), 'messaging')),
	path('', include(('apps.wishlist.urls', 'wishlist'), 'wishlist')),
	path('', include(('apps.shopping.urls', 'shopping'), 'shopping')),
	path('', include(('apps.notification.urls', 'notification'), 'notification')),
	path('', include(('apps.location.urls', 'location'), 'location')),
	path('', include(('apps.auction.urls', 'auction'), 'auction')),
	path('', include(('apps.advertisement.urls', 'advertisement'), 'advertisement')),

]

apps/product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MinLengthValidator
from taggit.managers import TaggableManager
from django.urls import reverse_lazy
from django.apps import apps
from django_jalali.db import models as jmodels
from apps.location.models import State, City, District
from apps.registeration.models import Customer
from backend_settings import settings
from utilities.notification_tools import notify
from utilities.validators import validate_existing_category, validate_customer_has_credit
# Create your models here.
from utilities.storage import OverwriteStorage


class Category(models.Model):
	parent = models.ForeignKey('self', verbose_name="دسته بندی پدر", on_delete=models.CASCADE, null=True)
	name = models.CharField("نام", max_length=50, unique=True)
	description = models.TextField("توضیحات", max_length=50, default="توضیحی ندارد.")
	
	class Meta:
		verbose_name = 'دسته'
		verbose_name_plural = 'دسته‌ها'

	def get_url(self, ):
		return reverse_lazy("landing:search", kwargs={"categoryid": self.id})

	def get_category_and_its_children(self):
		result = [self]
		children = Category.objects.filter(parent=self)
		for child in children:
			result += child.get_category_and_its_children()
		return result

	def get_level_one_children(self):
		children = Category.objects.filter(parent=self)
		return children

	@staticmethod
	def get_categories_json(dest):
		root = Category.objects.get(parent=None)
		successors = Category.objects.filter(parent=root)
		# result = [Category._get_category_json(succ, dest) for succ in successors]
		return [Category._get_category_json(root, dest)]

	@staticmethod
	def _get_category_json(node, dest):
		successors = Category.objects.filter(parent=node)
		json = {
			"id": node.id,
			"name": node.name,
			"desc": node.description,
			"is_active": node.id == dest,
			"url": node.get_url(),
			"succs": [],
		}
		for succ in successors:
			temp = Category._get_category_json(succ, dest)
			if temp["is_active"]:
				json["is_active"] = True
			json["succs"].append(temp)

		return json

	def __str__(self):
		return self.name


product_state_choices = (('کاملا نو', 'کاملا نو'),
						 ('در حد نو', 'در حد نو'),
						 ('استفاده شده', 'استفاده شده'),
						 ('کهنه', 'کهنه')
						 )


class Product(models.Model):
	name = models.CharField("محصول", max_length=50)
	creator = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
	price = models.IntegerField("قیمت", validators=[MinValueValidator(0, message="مقدار داده شده باید مثبت باشد.")])
	quantity = models.IntegerField("تعداد کل",
								   validators=[
									   MinValueValidator(0, message="مقدار داده شده باید عدد صحبح مثبت باشد.")])
	remaining = models.IntegerField("تعداد باقی‌مانده", blank=True, null=True)
	description = models.TextField("توضیحات",
								   validators=[MinLengthValidator(50, "توضیحات شما باید حداقل ۵۰ کاراکتر باشد")])
	district = models.ForeignKey(District, verbose_name="محله", null=True, on_delete=models.SET_NULL, blank=True)
	city = models.ForeignKey(City, verbose_name="شهر", null=True, on_delete=models.SET_NULL, blank=True)
	state = models.ForeignKey(State, verbose_name="استان", null=True, on_delete=models.SET_NULL, blank=True)
	category = models.ForeignKey(Category, verbose_name="دسته", on_delete=models.SET_NULL, null=True)
	image = models.ImageField(verbose_name="تصویر", null=True, storage=OverwriteStorage())
	product_state = models.CharField(verbose_name='وضعیت', choices=product_state_choices, max_length=20, null=True)
	material = models.CharField(verbose_name='جنس', max_length=20, null=True)
	is_trending = models.BooleanField(default=False,verbose_name='آیا ترند است')
	is_auction = models.BooleanField(default=False,verbose_name='آیا مزایده است')
	auction = models.OneToOneField("auction.Auction", verbose_name="حراج", null=True, on_delete=models.SET_NULL, blank=True)
	tags = TaggableManager(verbose_name='برچسب‌ها', help_text="لیستی از تگ ها که با ',' جدا شده اند")
	suggested_new_category = models.CharField(verbose_name="نام دستهٔ پیشنهادی جدید", max_length=50,
							null = True,blank = True, help_text="در صورتی که به نظرتان دستهٔ مورد نظر شما در دسته‌های بالا موجود نبود نام دستهٔ مورد نظر خود را وارد کنید.", validators = [validate_existing_category])

	class Meta:
		verbose_name = 'کالا'
		verbose_name_plural = 'کالاها'

	def clean(self):
		if self.is_auction:
			validate_customer_has_credit(self.creator,self.price/10)
		return super().clean()

	def __str__(self):
		return self.name + " به شناسهٔ " + str(self.id)

	@property
	def location(self):
		result = ""
		if self.district:
			result += str(self.district) + ","
		if self.city:
			result += str(self.city) + ","
		if self.state:
			result += str(self.state) + ","
		return result

	@property
	def url(self):
		return reverse_lazy('product:product-details', kwargs={"pk": self.id})

	@property
	def remained(self):
		return self.remaining > 0

	def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
		
		if self.pk is None:
			self.remaining = self.quantity
			print(self.remaining)
			result = super().save(force_insert=force_insert, force_update=force_update, using=using,
								  update_fields=update_fields)

			print(self.remaining)

			qs = apps.get_model("wishlist", "Wishlist").objects.all()

			qs = qs.exclude(min_price__gte=self.price)
			qs = qs.exclude(min_price__lte=self.price)

			if self.state:
				qs = qs.filter(state=self.state) | qs.filter(state=None)

			if self.city:
				qs = qs.filter(city=self.city) | qs.filter(city=None)
			if self.district:
				qs = qs.filter(district=self.district) | qs.filter(district=None)
			if self.tags:
				qs = qs.filter(tags__name__in=self.tags.names()) | qs.filter(tags=None)

			if self.category:
				qs = qs.filter(category=self.category) | qs.filter(category=None)
			temp = []
			target = self.name.split() + self.description.split()
			for wishlist in qs:
				if wishlist.text:
					counter = 0
					words = wishlist.text.split()
					for word in words:
						if word in target:
							counter += 1
					if counter / len(words) > 0.6:
						temp.append(wishlist)
				else:
					temp.append(wishlist)
			qs = temp
			for wishlist in qs:
				message = "اضافه شدن کالای درخواستی به سامانه\n" + "کالای " + self.name + "به شماره‌ٔ شناسهٔ " + str(
					self.id) + " مربوط به کالاهای مورد نظر شما است."
				notify("اضافه شدن کالای جدید به سامانه", message, wishlist.user.username)
		else:
			result =  super().save(force_insert=force_insert, force_update=force_update, using=using,
							update_fields=update_fields)

		if not self.suggested_new_category == None:
				RequestedCategory(name = self.suggested_new_category, product = Product.objects.get(pk = self.pk), parent_category = self.category).save()

		return result


class Comment(models.Model):
	user = models.ForeignKey(Customer, verbose_name="کاربر", on_delete=models.CASCADE)
	product = models.ForeignKey(Product, verbose_name="کالا", on_delete=models.CASCADE)
	title = models.CharField("عنوان", max_length=50)
	text = models.TextField("متن", validators=[MinLengthValidator(50, "توضیحات شما باید حداقل ۵۰ کاراکتر باشد")])
	date = jmodels.jDateTimeField(auto_now_add=True)

class RequestedCategory(models.Model):
	name = models.CharField("عنوان", max_length=50)
	product = models.ForeignKey(Product, verbose_name="کالا", on_delete=models.CASCADE)
	parent_category = models.ForeignKey(Category, verbose_name="دستهٔ پدر", on_delete=models.SET_NULL, null=True)
	seen = models.BooleanField(verbose_name="بررسی شده", default=False)
	implemented = models.BooleanField(verbose_name="ساخته شود", default=False)

	class Meta:
		verbose_name = 'پیشنهاد دسته'
		verbose_name_plural = 'پیشینهاد‌های دسته'

	def __str__(self):
		return self.name

	def clean(self):
		if self.implemented:
			validate_existing_category(self.name)
		return super().clean()

	def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
		if self.pk:
			original = RequestedCategory.objects.get(pk = self.pk)
			if self.implemented and not original.implemented:
				self.seen = True
				new_cat = Category(parent = self.parent_category, name = self.name)
				new_cat.save()
				new_cat = Category.objects.get(pk = new_cat.pk)
				self.product.category = new_cat
				self.product.suggested_new_category = None
				self.product.save()
		return super().save(force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)

apps/product/views.py
import simplejson
from django.http import HttpResponse
from django.views import View
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from dateutil import relativedelta
import datetime
from apps.location.models import *
from apps.notification.models import Notification
from apps.product.models import Product, Comment, Category
from apps.product.forms import ComparisonForm, ProductCreationForm
from apps.registeration.models import Customer
from apps.auction.models import Auction
from apps.shopping.models import Transaction
import jdatetime

class ProductCompareView(FormView):
	form_class = ComparisonForm
	template_name = "product/comparison.html"

	def get_context_data(self, **kwargs):
		data = super().get_context_data(**kwargs)
		self.pk1 = self.kwargs["pk1"]
		self.pk2 = self.kwargs["pk2"]
		try:
			product1 = Product.objects.get(id=self.pk1)
		except Exception:
			product1 = None
		try:
			product2 = Product.objects.get(id=self.pk2)
		except Exception:
			product2 = None
		data["product1"] = product1
		data["product2"] = product2
		return data

	def form_valid(self, form):
		product1 = form.cleaned_data.get("product1")
		product2 = form.cleaned_data.get("product2")
		self.pk1 = product1.id
		self.pk2 = product2.id
		return super().form_valid(form)

	def get_success_url(self):
		# TODO use reverse
		# return reverse_lazy("product:comparison",self.pk1,self.pk2)
		return str(self.pk1) + "," + str(self.pk2)

	def get_initial(self):
		"""
		Returns the initial data to use for forms on this view.
		"""
		initial = super().get_initial()
		initial['product1'] = self.kwargs["pk1"]
		initial['product2'] = self.kwargs["pk2"]

		return initial


class ProductDetailView(CreateView):
	model = Comment
	template_name = "product/product_details.html"

	def get_success_url(self):
		# TODO use reverse
		# return reverse_lazy("product:product-detail",self.kwargs["pk"])
		return str(self.kwargs["pk"])

	fields = [
		"title",
		"text",
	]

	def get_context_data(self, **kwargs):
		data = super().get_context_data(**kwargs)
		try:
			data["object"] = Product.objects.get(id=self.kwargs["pk"])
			self.product = data["object"]

		except Exception as e:
			print("faiielll")
		comments = Comment.objects.filter(product=self.product).order_by('date')
		data["comments"] = comments
		if self.product.is_auction:
			data["date"] =  self.product.auction.finish_date.togregorian()
			data["send_date"] =  self.product.auction.send_date.togregorian()
			data["pay_date"] =  self.product.auction.pay_date.togregorian()
		related_category = self.product.category
		if related_category.parent:
			related_category = related_category.parent
		data["relateds"] = Product.objects.filter(category__in=related_category.get_category_and_its_children())[:5]
		return data

	def form_valid(self, form):
		user = self.request.user
		form.instance.user = Customer.objects.get(id = user.id)
		form.instance.product = Product.objects.get(id=self.kwargs["pk"])
		return super().form_valid(form)


class ProductCreateView(LoginRequiredMixin, CreateView):
	form_class = ProductCreationForm
	template_name = "product/create_product.html"

	def get_success_url(self):
		if self.is_auction:
			return reverse_lazy("auction:create-auction", kwargs={'pk': self.object.auction.id })
		else:
			return reverse_lazy("landing:landing")
	
	def post(self, request, *args, **kwargs):
		self.object = None
		form = self.get_form()
		creator = Customer.objects.get(username = self.request.user.username)
		form.instance.creator = creator
		if form.is_valid():
			return self.form_valid(form)
		else:
			return self.form_invalid(form)

	def form_valid(self, form):
		user = self.request.user
		customer = Customer.objects.get(username=user.username)
		form.instance.creator = customer
		self.is_auction = form.instance.is_auction
		finish_date = datetime.datetime.now() + relativedelta.relativedelta(days=28)
		pay_date = datetime.datetime.now() + relativedelta.relativedelta(days=30)
		send_date = datetime.datetime.now() + relativedelta.relativedelta(days=32)
		start_transaction = Transaction(amount = form.instance.price/50, source_user = form.instance.creator, type = 'ودیعه')
		start_transaction.save()
		start_transaction = Transaction.objects.get(id = start_transaction.id)
		auction = Auction(finish_date = finish_date, pay_date = pay_date, send_date = send_date, price = form.instance.price, start_transaction=start_transaction)
		auction.save()
		auction = Auction.objects.get(pk = auction.pk)
		form.instance.auction = auction
		return super(ProductCreateView, self).form_valid(form)

	def form_invalid(self, form):
		return super().form_invalid(form)

	def get_context_data(self, **kwargs):
		context = super(ProductCreateView, self).get_context_data(**kwargs)
		context['first_category'] = {c['id']: c['name'] for c in Category.get_categories_json(-1)[0]['succs']}
		context['second_category'] = {}
		context['third_category'] = {}

		context['first_category'][0] = "سایر"
		context['second_category'][0] = "سایر"
		context['third_category'][0] = "سایر"
		context['locations'] = Location.objects.filter(customer_id=self.request.user.id)
		return context


def get_category_childs_one_level(request, category_id=1):
	print('was here ! :D')
	category = Category.objects.get(id=category_id)
	family = category.get_level_one_children()
	cat_dict = {}
	for cat in family:
		cat_dict[cat.id] = cat.name

	cat_dict[0] = 'سایر'
	h = HttpResponse(simplejson.dumps(cat_dict), content_type='application/json')
	return h

apps/product/templates/product/comparison.html
<!-- transactions : transactions -->
{% extends "dashboard/mother_panel.html" %}
{% load static staticfiles %}


{% block title %}
مقایسهٔ کالا
{% endblock title %}

{% block sidebar %}

{% include "dashboard/sidebar.html" %}

{% endblock sidebar %}
<header class="main-header">
    {% block header %}
    <!-- Logo -->
    <a href='#' class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <!-- logo for regular state and mobile devices --><strong>مقایسهٔ کالا</strong><br>
    </a>
    {% block navbar %}

    {% include "landing/navbar.html" %}

    {% endblock navbar %}
    {% endblock header %}
</header>

{% block main_content %}
<div class="col-xs-6">
    <form method="post" enctype="multipart/form-data" novalidate>{% csrf_token %}
        <table class="table">
            <tbody>
            {% for field in form %}
                <tr>
                    <th><label for="id_name">{{ field.label_tag }}</label></th>
                    <td>
                        {% if field.errors %}
                          <ul>
                            {% for error in field.errors %}
                              <li>{{ error }}</li>
                            {% endfor %}
                          </ul>
                        {% endif %}
                        {{ field }}
                        {% if field.help_text %}
                          <br />{{ field.help_text }}
                        {% endif %}
                      </td>
                </tr>
                {% endfor %}
                {% if form.non_field_errors %}
                <ul>
                    {{ form.non_field_errors.as_ul }}
                </ul>
                {% endif %}
            </table>
        <input type="submit" value="مقایسه کن">
    </form>
</div>
<div class="row">
    <div class="col-xs-12">
        <div>
            <table class="table">
                <tbody>
                <tr>
                        <td></td>
                    <td><img src="{{ product1.image.url }}"></td>
                    <td><img src="{{ product2.image.url }}"></td>
                </tr>
                <tr>
                    <th>نام</th>
                    <td>{{product1.name}}</td>
                    <td>{{product2.name}}</td>
                </tr>
                <tr>
                    <th>فروشنده</th>
                    <td>{{product1.creator}}</td>
                    <td>{{product2.creator}}</td>
                </tr>
                <tr>
                    <th>تعداد باقی‌مانده</th>
                    <td>{{product1.quantity}}</td>
                    <td>{{product2.quantity}}</td>
                </tr>
                <tr>
                    <th>قیمت</th>
                    <td>{{product1.price}}</td>
                    <td>{{product2.price}}</td>
                </tr>
                <tr>
                    <th>دسته</th>
                    <td>{{product1.category.name}}</td>
                    <td>{{product2.category.name}}</td>
                </tr>
                <tr>
                    <th>جنس</th>
                    <td>{{product1.material}}</td>
                    <td>{{product2.material}}</td>
                </tr>
                <tr>
                    <th>وضعیت</th>
                    <td>{{product1.product_state}}</td>
                    <td>{{product2.product_state}}</td>
                </tr>
                <tr>
                    <th>مکان</th>
                    <td>{{product1.location}}</td>
                    <td>{{product2.location}}</td>
                </tr>
                <tr>
                    <th>توضیحات</th>
                    <td>{{product1.description}}</td>
                    <td>{{product2.description}}</td>
                </tr>
                <tr>
                    <th>برچسب‌ها</th>
                    <td>{% for tag in product1.tags.all %}
                        {{ tag.name }},
                        {% endfor %}
                    </td>
                    <td>{% for tag in product2.tags.all %}
                        {{ tag.name }},
                        {% endfor %}
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock main_content %}